- name: copying rsyslog config file
  ansible.builtin.template:
   src: rsyslog.conf
   dest: /etc/rsyslog.d/{{component}}.conf
  when: is_rsyslog_needed

- name: restarting rsyslog
  ansible.builtin.systemd:
   name: rsyslog
   state: restarted
   enabled: yes
  when: is_rsyslog_needed

- name: Copying elastic repo file
  ansible.builtin.template:
   src: elastic.repo
   dest: /etc/yum.repos.d/elastic.repo

- name: Installing filebeat
  ansible.builtin.dnf:
   name: filebeat
   state: installed

- name: copying filebeat config file
  ansible.builtin.template:
   src: filebeat.yml
   dest: /etc/filebeat/filebeat.yml

- name: Restarting filebeat service
  ansible.builtin.systemd:
   name: filebeat
   state: restarted
   enabled: yes
