- name: Set hostname
  ansible.builtin.shell: set-hostname {{env}}-{{component}}

- name: Disable nodejs default version
  ansible.builtin.shell: dnf module disable nodejs -y

- name: Enable nodejs:18 -y
  ansible.builtin.shell: dnf module enable nodejs:18 -y

- name: Installig nodejs 
  ansible.builtin.dnf:
   name: nodejs
   state: present

- name: Copy backend service
  ansible.builtin.template:
   src: catalogue.service
   dest: /etc/systemd/system/catalogue.service

- name: Add application user
  ansible.builtin.user:
   name: expense

- name: Importing app pre requisites
  ansible.builtin.import_role:
   name: common
   tasks_from: app-prereq
  vars:
   app_dir: /app
   component: backend
   app_user: expense

- name: Installing nodejs dependencies
  ansible.builtin.shell: npm install    
  args:
   chdir: /app

- name: Install newrelic nodejs libaray
  ansible.builtin.shell: npm install newrelic --save
  args:
   chdir: /app

- name: Copy newrelic nodejs startup script file
  ansible.builtin.template:
   src: run.sh
   dest: /app/run.sh

- name: Copy Mongodb repo file
  ansible.builtin.template:
   src: mongo.repo
   dest: etc/yum.repos.d/mongo.repo

- name: Installing Mongodb client
  ansible.builtin.dnf:
   name: mongodb-org-shell
   state: installed

- name: Importing elk configuration file
  ansible.builtin.import_role:  
   name: elk
   tasks_from: filebeat

- name: Importing node-exporter file
  ansible.builtin.import_role:
   name: prometheus
   tasks_from: node-exporter

