- name: Downloading and extracting node-exporter file
  ansible.builtin.unarchive:
   src: https://github.com/prometheus/node_exporter/releases/download/v1.7.0/node_exporter-1.7.0.linux-amd64.tar.gz
   dest: /opt
   remote_src: yes

- name: copy service file
  ansible.builtin.template:
   src: node-exporter.service
   dest: /etc/systemd/system/node-exporter.service

- name: Start systemd service
  ansible.builtin.systemd:
   name: node-exporter
   state: restarted
   enabled: yes
   daemon-reload: yes


- name: Importing grafana file
  ansible.builtin.import_role:
   name: grafana

- name: Import prometheus alert-rule-update.yml  
  ansible.builtin.import_role:
   name: prometheus
   tasks_from: alert-rule-update 

