   -  name: Deleting old nginx content
      ansible.builtin.file:
       name: "{{ app_dir }}"
       state: absent

   -  name: Creating  nginx directory
      ansible.builtin.file:
       name: "{{ app_dir }}"
       state: directory
       owner: "{{app_user}}"
       group: "{{app_user}}"

   -  name: Downlaoding and extracting content
      ansible.builtin.unarchive:
       src: https://roboshop-artifacts.s3.amazonaws.com/{{component}}.zip 
       dest: "{{ app_dir }}"
       remote_src: yes
       